exclude: .git|migrations|.vscode
default_stages: [push, commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']

-   repo: local
    hooks:
    -   id: black
        name: black
        stages: [commit]
        types: [python]
        language: system
        pass_filenames: false
        entry: make black

-   repo: local
    hooks:
    -   id: isort
        name: isort
        stages: [commit]
        types: [python]
        language: system
        pass_filenames: false
        entry: make isort

# -   repo: local
#     hooks:
#     -   id: flake8
#         name: flake8
#         types: [python]
#         language: system
#         pass_filenames: false
#         entry: flake8

# -   repo: local
#     hooks:
#     -   id: mypy
#         name: mypy
#         types: [python]
#         language: system
#         pass_filenames: false
#         entry: "mypy ."
