version: '3.8'

services:
  web:
    build: .
    entrypoint: /usr/src/app/entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  celery-worker:
    restart: unless-stopped
    build: .
    entrypoint: /usr/src/app/worker-entrypoint.sh
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    depends_on:
        - web
        - redis
  celery-beat:
    restart: unless-stopped
    build: .
    entrypoint: /usr/src/app/beat-entrypoint.sh
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    depends_on:
        - web
        - redis
        - celery-worker
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

volumes:
  postgres_data:
