[tool.poetry]
name = "website"
version = "0.1.0"
description = ""
authors = ["cookieblues <cookieblues@outlook.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
