name: Build, Push, and Deploy Image

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#     types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build-push-image:
    name: Build and push image
    # if: ${{ !github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 1200
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.stage.yml build
      - name: Push Docker image
        run: |
          docker-compose -f docker-compose.stage.yml push